[[P4est]]
arch = "aarch64"
git-tree-sha1 = "7ae7c0f8182c21d1508ce9445716c34969a853af"
os = "macos"

    [[P4est.download]]
    sha256 = "4f4bbcc2ecc38cccc8fdaee36669f422abcc0ddf8720e0dab52e6fe05f67ea54"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.aarch64-apple-darwin.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "1175d438cf3cace69c6851a259965ea96ff9b266"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "8beeeab29dfbd03abff1e06c7078b4f24eced1d66ac6c0f5cca65da7f068d8fb"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.aarch64-linux-gnu.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "b2d2a3e941fb2bb5f2b316ce53d4b2a25aef3a16"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "285aa2c95a36bdcdcf535dcd08df16e163ff1ae49e6b9485337a7c1f5e843d07"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.aarch64-linux-musl.tar.gz"
[[P4est]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "d5c6826b3ea0c228f445dcf4884275eaccced4a8"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "ed08e9b608707d67795b1f2e0116f2111e73cf97d6f1e94beaa647099aec287b"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.armv6l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "b7f88667ead1a07ccfd2f029a6525b8f7c06283d"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "c52fd1761b1890779bc84851d635dab87963bf8f30b760ff08c1f94de2635624"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.armv6l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "4e99bee177b3993b3a10df96627d4e24d7ad6afd"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "51518d3a58a8efed6aa7b29f1a02e8b3bb85686095e5284c047e1409deaa7b92"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.armv7l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6a45aaf6615ba1e9276e48aaccf5264d58716f3c"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "7719efd90f3c84c22606434dd6372255694b94586de5a021086c5a9faf541bdd"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.armv7l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "f9b0ae0097f242265e0e9f203f1d6f3f21874751"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "d26f6ea25af80f6f9877463e56de58efb6aebaa624c42293c28a5df2ab068b1d"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.i686-linux-gnu.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "7324fcfa08613250f5e0781f61dddf1cde63bd86"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "2212bc6b98b35e2a55eb62cad8a45f44c50f9691ae5b64c04fd7611f56f69e9d"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.i686-linux-musl.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "9e216a79076567d28794ce0c749e23eb827aace1"
os = "windows"

    [[P4est.download]]
    sha256 = "de9b04a75a160a648c0a4e53ce0c343dbfcab38e25a6f5cf637b9912515b6297"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.i686-w64-mingw32.tar.gz"
[[P4est]]
arch = "powerpc64le"
git-tree-sha1 = "26c4a973cebc8c8fb4fe82dded7b431b989d0bab"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "ff588a3d955d37af6b7df4485840ef8a3379f5bfcff3b3a130c187e32fa5b7e4"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.powerpc64le-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "30ee4cbbbf5611ec1c370c8e641f66ab4c9bac30"
os = "macos"

    [[P4est.download]]
    sha256 = "0af5968668746f595237060b419f5ba11c7c0c3aa6d447dd06c2223904e155e5"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.x86_64-apple-darwin.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "93e47e83c32f82f4f1f2c6b99a38aaee8db33090"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "ebc39ebfb1cd8a4a37ac7c7fb5813977a5188461e00879a67278e9b22ef304c4"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.x86_64-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "f35c65cefed08f7bcdac6f887fbf4285b4d79ceb"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "874d6171621c22087deaccf01cbf0085069a74e0b8f7eebcab5a53989a6aa18b"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.x86_64-linux-musl.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "2fc24079d9acd4a3fcdb2c28c3568166885cba9e"
os = "freebsd"

    [[P4est.download]]
    sha256 = "23c87bf3f907a961456e98910ca2528c705bf6297a927eb5cae7f8bdc146c908"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.x86_64-unknown-freebsd.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "53011283ad3de642f7b0e00bcb220373e94835ae"
os = "windows"

    [[P4est.download]]
    sha256 = "52e3273530fe9a5cfc939a6ac8e025c0c03a0b154c1cf01febb3f69d3adb8300"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.2+0/P4est.v2.3.2.x86_64-w64-mingw32.tar.gz"
