[[P4est]]
arch = "aarch64"
git-tree-sha1 = "1a301daed2712b77328f00875eec4b708d7719a2"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "032f930a9339bb52bf45026020538fa2f99ddf6eca74b9e2dbf5a50f804c29f0"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.aarch64-linux-musl.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "5fb7cad2dc76409e79bd4821f895e6ba9795ae27"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "0df17fd2b8ee680ef2804d5719b88175a8a920b05a8aad2588ed71b383336914"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.x86_64-linux-musl.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "0dee92ac7a5be012f97b78d81a572b262f1165b7"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "1011e6cf2c17464aa54153aca1e472fd6995180e127d0564737e82cfdf22fdee"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.i686-linux-gnu.tar.gz"
[[P4est]]
arch = "armv7l"
git-tree-sha1 = "5f3db86ecaebbe55d0361db112561add118ade04"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "e6533fc033b70858b4a4ac94a259cc95d2ab87b82d519b04f4b22b49e654d030"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "94e71efdcd90f186ae66ade89328d7864c5320d0"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "ba13da6b71d82f3a37f872171da6913e2e681aabecb09708efbd49b2fcf006dc"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.aarch64-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "07700f3d7f0f5bf702b0dda4a3a0488aba90a3a0"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "e39c9fc369017856e0604a6ed2d49c485846d3b9940c3dfca54c171db1f61163"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.x86_64-linux-gnu.tar.gz"
[[P4est]]
arch = "powerpc64le"
git-tree-sha1 = "f96105aa63a88c242b210016058a9dcf12390095"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "f4af58001d632f7e29041f013fa0a0e2ee3d62fe81b502de35b60a32c90ef08f"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "a1d04827a5c34a6f62fe3d7f82a5fedff1c53828"
os = "macos"

    [[P4est.download]]
    sha256 = "491f5e38d0f2362aa1f5fd08f1070cbd1c70f1814c703b725aa34af920136b2e"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.x86_64-apple-darwin14.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "694e51b2f797e434a0d5dffff37b6f99887a1dd8"
os = "freebsd"

    [[P4est.download]]
    sha256 = "f67a4ca8537604e88275539c2b89c1f57783e4084304c9bd70c185aa9ad7458a"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.x86_64-unknown-freebsd11.1.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "c761bc1709ee96bc647f624c33126c9af2d161bc"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "00710ba80d7289f46699f179fb4a7ada13360acb01d095f07626f7a643c701aa"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.i686-linux-musl.tar.gz"
[[P4est]]
arch = "armv7l"
git-tree-sha1 = "5f46881502b3e5d897d38ce9f60950662d076f0c"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "fd4ab218b4d12e5dcfaebf207bbe437d8d47b7b79312e7b279f3347b905a31a6"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+0/P4est.v2.2.0.armv7l-linux-musleabihf.tar.gz"
