[[P4est]]
arch = "aarch64"
git-tree-sha1 = "f7932be015ed6a370c24f1caf59870c7653c76e4"
os = "macos"

    [[P4est.download]]
    sha256 = "099624e0cec6eb93a52e5b754b27b6f2b4f2a11ec50048a9397992c8ee65fc55"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.aarch64-apple-darwin.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "31182e4204c762d5855a58c4b30fbd39c29b8203"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "92fb1cbc7e383cf009ab2a7ede525c344232562205bc5762f55bf64a5fd8ed18"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.aarch64-linux-gnu.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "b2baacba2ae4c19e18c26eb7badfe58a479b60ba"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "b35a9fa69689296c8126aae4e26b89aad3c22abdb8581e406bbd927228aaa4e1"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.aarch64-linux-musl.tar.gz"
[[P4est]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "374ee193c6cc2731727b7a05f29f1c744924e564"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "b69af77085b597d2ed49e2b05983607e679e078aa096164ebf993984b89d1f5e"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.armv6l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "3fa60d90e6fa6595f24e11ecda7f7037d23d415e"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "982578cca5eda27c3336f52d754696336ac547f1f06375ee68e3f39647351583"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.armv6l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "5ac34c90dfac1a9bacff26d6916b27a3f163fa27"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "32f5f08883970a582ccfd15179c8b8bdd35dad8b88325e05dbb8034e83d9b268"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.armv7l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8e25f3f866788f790a5b6690e900032430301e6f"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "256cf44d27adb8e24024c85ee70212ec3c7aecc7273f1312ecd868c1cba73b6b"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.armv7l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "7aaa92e44411e308d1f9e8e4c0b4972f455d9e53"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "2d92c7f2ffca5374846554f8f570d1055d2ac7d1fb534fb659a7dc82a1ba951f"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.i686-linux-gnu.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "b4aaba1bb61c8dd17671c9f30bddca65012094d9"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "7571d79963c2e2266312b4674df22569b4eb26ba1fb2cca953ad2c3bffe8e418"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.i686-linux-musl.tar.gz"
[[P4est]]
arch = "powerpc64le"
git-tree-sha1 = "84c233a7460a815ce59440744f6c0e91578ee2f6"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "838b5e34be2b10b4952c4e00241fd1f7281502cf7ac03c55e7727f3e7195f262"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.powerpc64le-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "4215f7fb21151ff19e2075d10e0677c031fc8dee"
os = "macos"

    [[P4est.download]]
    sha256 = "4e03984f085b471a0118ee3e839393e60e46002e5df3f637e32afe1b2757a9e5"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.x86_64-apple-darwin.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "0a2d5cebfd9e9b6072a1283ba38086a7e8211f37"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "b951e1c3c0d36c25e72c94ac8ac2665f80efa323018353ec221f3cd8be144fc0"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.x86_64-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "79db824271502017333e4cbb70d7f9a51c72805a"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "1558760838624c8a09503f7e3bbae03d4dbe89d590abea9fb04b7aa444a330a0"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.x86_64-linux-musl.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "41996cef606b4d1beade0ac1f30527b17479b017"
os = "freebsd"

    [[P4est.download]]
    sha256 = "24b61c9e858e08213a3cdb0a87bfeab497d33b5fe6747ec4730d78f65669ca97"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.x86_64-unknown-freebsd.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "392171f795bd93050fd8f01e5b41bed8c03fe3db"
os = "windows"

    [[P4est.download]]
    sha256 = "eddcf6f04c2597a61249db49a3cd5cc6e4f74e3d420266cd84cf4e1cd63b58b8"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.8.0+0/P4est.v2.8.0.x86_64-w64-mingw32.tar.gz"
