[[P4est]]
arch = "aarch64"
git-tree-sha1 = "e821d282510670587a8d0bd516933587ae3c031d"
os = "macos"

    [[P4est.download]]
    sha256 = "2c47a3027755e94abe7b6eee9a7060c56554aa3812c16f8f4a221ce0a6d3c571"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.aarch64-apple-darwin.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "05a83ad3ce1bdc0ca3634341c5dd5995b69f99e7"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "8562324a2419d61f271655490e803a8a442d96797685e5f5f3b20ee81953f8ae"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.aarch64-linux-gnu.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "9ac6d62298d17eedd93836604fcaa810ef12a903"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "3f5b55418613b560d89c66d5655c6dbdecb482cf25dd2259fd574de414b218f2"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.aarch64-linux-musl.tar.gz"
[[P4est]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "eee4e9bfbe20b4204d5a47756b23e99256920304"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "cda360da6fd5088c4e621675201c9b0140d4528b63cdd0a3ca9c5212fabcae88"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.armv6l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "750e99bbb43515c2b498893c1fd7f6f7d5f0a25f"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "b428f33a42078b7d2f7f0378c5c7a52ce5882d65043fe55274eae58a2108d3fe"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.armv6l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "6aa7e39eb698728747838c975cc81627de709df7"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "5907fa8faf513a5113835af87df86d3446f3622236551a4170b5c652def992c9"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.armv7l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "3ca832ee4ce7e0d6b86495ef56f89fd672c83474"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "b98aa3e7696d5ad83230b6ea11f6c837b140cdb6fa311f6703fee766cb0972b7"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.armv7l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "18d08c1af7397d15c70d61ac7a499a5fda3964bb"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "e4d12550cbf0690e556cf3baf5acbc2e54d10b120517055e24ca422baa0fcbf3"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.i686-linux-gnu.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "3357ca091eed30ba9d2b5baf69a0696ec4c564fb"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "0fde686bbd2309512703cb5cb7fafa291797436b7a1c7f1b31bdb0f537066c6d"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.i686-linux-musl.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "5c2c9a4dc94a5095a15675af693b3f21c3348d08"
os = "windows"

    [[P4est.download]]
    sha256 = "330d203aec7afe726014705cb8121c4363ce003e3aeaf6630006d18b2c705040"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.i686-w64-mingw32.tar.gz"
[[P4est]]
arch = "powerpc64le"
git-tree-sha1 = "3350ce6a500db66501011b7b83b2cf5598a061a3"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "23f29c942ae8b62aa5ee70174a63cd952ef192f7a5aefe36bd86df3b94a7ca8a"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.powerpc64le-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "354cc538b24cdca11cf83cad2eaa5c3950def8cd"
os = "macos"

    [[P4est.download]]
    sha256 = "0519abc3fcd68406ecfd41a29104494e43fb1c9adfeddbb101cbc1fa38d6f7e6"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.x86_64-apple-darwin.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "c165ee46c10d3a09ce22453ff9133e67e93bdef3"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "ce4b576c70b6bd336012b926ae7900fdb77a2a5f509a93b4922e54d46535dcad"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.x86_64-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "e9e4b8ab9bdb772a45ea6d90118366953aad7a84"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "943fe2a673ed7eed3df12a6bad0a305d5a123041ee3b1dee93789d70ccb6897f"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.x86_64-linux-musl.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "2bd2c81a4d0d75b961c572f92e4b0bd398b29a1b"
os = "freebsd"

    [[P4est.download]]
    sha256 = "e21d286f4059f1f7d2ab6b8e8bcb433afb7b52eb9150f52cdb2276733f871094"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.x86_64-unknown-freebsd.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "052a21e63939acf469d535a54a3e30c4154990cf"
os = "windows"

    [[P4est.download]]
    sha256 = "a500697d89e38251a9dcd03a2106585d183709d58be16e6e538b767dd0a6876b"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+1/P4est.v2.3.1.x86_64-w64-mingw32.tar.gz"
