[[P4est]]
arch = "aarch64"
git-tree-sha1 = "3aa3164b7562987a0e95356793b6d760611390e6"
os = "macos"

    [[P4est.download]]
    sha256 = "23a32925a7025f4f7d7b088c927f213626753a7468719ace47b8a8650f2d8d4a"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.aarch64-apple-darwin.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "a6d1e1d3a8d63baaa8c67c86190b831d8ccfea11"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "bd8b789ddcaea63dca39d14d63ec5c0d30ff9f22f97346a3d14e2ae6c92874cc"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.aarch64-linux-gnu.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "3e84fc19f0d8e8172c137c36d28a662979349c80"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "f0359506532d474078b1ca6b4e294977ea4681ff29fd467a2cb26f307db3ae00"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.aarch64-linux-musl.tar.gz"
[[P4est]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "e0e786c21bc4b5c53b3cc3f0de9d90bcbc4343b9"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "56ced82928bf06603ff8aec398432bb218a281c2a8e1a376235b2adcb06998e3"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.armv6l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv6l"
call_abi = "eabihf"
git-tree-sha1 = "5c66405f00ef877a9e7240f38e961fb4adbaa8dc"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "63e89c0b4b6e7cee344edf5429649d7c75c04c2a09726d304bac796e43876040"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.armv6l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "8aba826e2e478f7213364a2c48afcdc26359b121"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "11acc35109851c9572e04e5e01d3d773772ede9b2675342c8db1ceb3daae7d5a"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.armv7l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ab2a19210fc7d1cf563af9bf98ee74d820f8e9ca"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "fa58bb3f42b4aa222a8a600b8ab0b422184cb7230e291df63e49b00dd4e5988d"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.armv7l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "77fbd8cda44a064a252529030f55eb0a43c11d3e"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "13bd1e6eced117f1e034259b51a9613ea1537a5e315174082581799a59599bd4"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.i686-linux-gnu.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "603148308f62d213af9083a3f6a16361f09152f7"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "45208a7d51bf1e597be2f0c7c4f97caf9c0620e0fef839a34423f735288b3484"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.i686-linux-musl.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "74efd758993b7275dcfaf66608e8ea6073a48634"
os = "windows"

    [[P4est.download]]
    sha256 = "40b7f2db1b82c589ebc4425427c71cc253764bd1c15e99723924eadbf0bdd9d7"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.i686-w64-mingw32.tar.gz"
[[P4est]]
arch = "powerpc64le"
git-tree-sha1 = "27f8a36f4dee2180a3eca525fe1464278c0a212d"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "4adb729929fd375dca4b872d86c2ba41f3a9947acccc68cba270db7ca3cd7dd1"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.powerpc64le-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "1575a340b6c89cb5e8a3eb5dd45a62bfb960a2f3"
os = "macos"

    [[P4est.download]]
    sha256 = "468c99591b234a6965d173198127b80be21b63b21afc579673c7c4fe6f0df96e"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.x86_64-apple-darwin.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "d93837ed7e8410d90c6d1ada8c9009d8ad906db2"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "7f12c67dc239e88324212a643d7b015a32d0abb7d700890171a56deef870fe8d"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.x86_64-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "f231269076eefeac0bc08e452d5b1a9cb720339a"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "a1b59ff1446fec9cd55066c4d2eb6f46303c8ca4febfea843eb7785a40ff8576"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.x86_64-linux-musl.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "684336cb6e6c723836de8f8ee9b22a981c49896d"
os = "freebsd"

    [[P4est.download]]
    sha256 = "3153230427dbdf5f29df33422263b46d3c7123e9191ff850d5b035ad275dc8a1"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.x86_64-unknown-freebsd.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "d8a12fde38210c907d2949d453ae8b09946aadc7"
os = "windows"

    [[P4est.download]]
    sha256 = "382bb5d7ae8685be43480273246e5a00145436580e510b928072c7806cd9e60a"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.3.1+0/P4est.v2.3.1.x86_64-w64-mingw32.tar.gz"
