[[P4est]]
arch = "aarch64"
git-tree-sha1 = "bc9f2d3ebba9d51a71c6ed6139554390547a0722"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "138cb97aa5ff68b982096b41d1db072d74ce481622926cf1fd75252655968c88"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.aarch64-linux-gnu.tar.gz"
[[P4est]]
arch = "aarch64"
git-tree-sha1 = "0543920bdcb6da106efd778d206bb887a8593dfa"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "f1eaa9562b4d7ed0dac4ebfb9f54e55ff7c65d44104fbce14cf8d48cfbe9d020"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.aarch64-linux-musl.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "ff9cd08b0d0ee208f5e02a623a62b4abfd6c9f3e"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "ef4fbddea87952d63a04dccfb0fe26db98318b74ed82b3bec61d8738cb65adf2"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.armv7l-linux-gnueabihf.tar.gz"
[[P4est]]
arch = "armv7l"
call_abi = "eabihf"
git-tree-sha1 = "0bc392c87d2456ae6e4c66d43a70ff5e0575e597"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "9dc23da4839154cb52baa6430c641cd38caa4ffb61099cd54e72d64c86f6a05b"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.armv7l-linux-musleabihf.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "da59b3a416e5392db010453026d5745f3fc915a7"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "b9c2ce36450b6d1f8e1cc39af5e2e9337dcc4947f7fef4ca94541bd2a3b617ca"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.i686-linux-gnu.tar.gz"
[[P4est]]
arch = "i686"
git-tree-sha1 = "31bff0245fa1bb0144842d2e37a513967812f6dd"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "966719711cf32e348d5bed945a4ad706194967f1954a54ef95b6c875bf8a6450"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.i686-linux-musl.tar.gz"
[[P4est]]
arch = "powerpc64le"
git-tree-sha1 = "202a01f7f62b49c6376d79abc8dbd8c991dd0b11"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "ce0db66feb2ee577fa9d4dde0afd632d184ef096687676de8794d7b6674c147a"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.powerpc64le-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "caafb6cdc58816c33aa4f41e555b04f25a6ac7e3"
os = "macos"

    [[P4est.download]]
    sha256 = "b290e3534aca5d8b9c518e3a80a78b865193be39c9df2e800eb6577b4ae441be"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.x86_64-apple-darwin.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "bb31421737f71afecd6a7760afa471cd27c9d211"
libc = "glibc"
os = "linux"

    [[P4est.download]]
    sha256 = "93e325133e9097ade5c40d25a7d97977b86b365245ad7dfcff317b3f5c23f963"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.x86_64-linux-gnu.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "bd9dea2e18ad4bc432a847fba1655923d4885719"
libc = "musl"
os = "linux"

    [[P4est.download]]
    sha256 = "dfd290fe688830bc6957c7023a27877fe1f4ea6af4bc4d7c3d3fc90fededbc1e"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.x86_64-linux-musl.tar.gz"
[[P4est]]
arch = "x86_64"
git-tree-sha1 = "f29aab51b15c652e340aa60da69ad4ea2e4c0667"
os = "freebsd"

    [[P4est.download]]
    sha256 = "f9a62c74620a50afdf25e78bba5adad3b2faed36b2d8a714fc4eb8c8e8af93db"
    url = "https://github.com/JuliaBinaryWrappers/P4est_jll.jl/releases/download/P4est-v2.2.0+2/P4est.v2.2.0.x86_64-unknown-freebsd.tar.gz"
