# Autogenerated wrapper script for P4est_jll for x86_64-w64-mingw32-mpi+microsoftmpi
export libp4est, libsc

using Zlib_jll
using MicrosoftMPI_jll
JLLWrappers.@generate_wrapper_header("P4est")
JLLWrappers.@declare_library_product(libp4est, "libp4est-0.dll")
JLLWrappers.@declare_library_product(libsc, "libsc-0.dll")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, MicrosoftMPI_jll, MPIPreferences)
    JLLWrappers.@init_library_product(
        libp4est,
        "bin\\libp4est-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsc,
        "bin\\libsc-0.dll",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
