# Autogenerated wrapper script for P4est_jll for x86_64-apple-darwin
export libp4est, libsc

using Zlib_jll
using OpenBLAS32_jll
JLLWrappers.@generate_wrapper_header("P4est")
JLLWrappers.@declare_library_product(libp4est, "@rpath/libp4est-2.2.dylib")
JLLWrappers.@declare_library_product(libsc, "@rpath/libsc-2.2.dylib")
function __init__()
    JLLWrappers.@generate_init_header(Zlib_jll, OpenBLAS32_jll)
    JLLWrappers.@init_library_product(
        libp4est,
        "lib/libp4est.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@init_library_product(
        libsc,
        "lib/libsc.dylib",
        RTLD_LAZY | RTLD_DEEPBIND,
    )

    JLLWrappers.@generate_init_footer()
end  # __init__()
